allowBuilds:
  '@parcel/watcher': true
  '@patternslib/dev': true
  unrs-resolver: true
  yarn: false

minimumReleaseAgeExclude:
  - svelte@5.56.3

overrides:
  "slick-carousel": "-"
  "slides": "-"

shamefullyHoist: true
